name: add_comment

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
           owner: context.repo.owner,
           repo: context.repo.repo,
           title: 'Daily issue',
           body: 'created'
          })
