on:
  issues:
    types: [opened,edited,reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run-script
        id: run-script
        run: |
          echo "::set-output name=output::$(./echo.bash)"
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.run-script.outputs.output }}"
            })
